codecov:
  require_ci_to_pass: true

comment:
   behavior: default
   branches:
      - 'master'

coverage:
   round: 'down'
   range: 95..100
   status:
      project:
         default:
            target: auto
            threshold: 0.1%

      # Lines adjusted in the PR
      patch:
         default:
            target: 98%
